name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Enable Pages for workflow builds (idempotent).
      # Tries GITHUB_TOKEN; if blocked by org policy, falls back to secrets.PAGES_ADMIN_TOKEN (optional).
      - name: Enable Pages (workflow builds)
        shell: bash
        env:
          GH_API: https://api.github.com
          PAGES_ADMIN_TOKEN: ${{ secrets.PAGES_ADMIN_TOKEN }}
        run: |
          set -euo pipefail
          repo="${GITHUB_REPOSITORY}"
          pages_url="${GH_API}/repos/${repo}/pages"
          payload='{"build_type":"workflow"}'

          has_pages() {
            curl -fsS -H "Accept: application/vnd.github+json" \
                 -H "Authorization: Bearer $1" \
                 "$pages_url" >/dev/null
          }
          enable_pages() {
            curl -fsS -X PUT -H "Accept: application/vnd.github+json" \
                 -H "Authorization: Bearer $1" \
                 -d "$payload" "$pages_url" >/dev/null
          }

          # Already enabled?
          if has_pages "${GITHUB_TOKEN}"; then
            echo "Pages already enabled."
            exit 0
          fi

          # Try with GITHUB_TOKEN (works for user repos / permissive orgs)
          if enable_pages "${GITHUB_TOKEN}"; then
            echo "Pages enabled with GITHUB_TOKEN."
            exit 0
          fi

          # Fallback PAT (classic: repo,pages OR FG: Contents:R, Pages:RW, Administration:RW)
          if [[ -n "${PAGES_ADMIN_TOKEN:-}" ]] && enable_pages "${PAGES_ADMIN_TOKEN}"; then
            echo "Pages enabled with PAGES_ADMIN_TOKEN."
            exit 0
          fi

          echo "::warning::Could not enable Pages automatically. If org policy blocks creation, set a PAT in PAGES_ADMIN_TOKEN or enable in Settings → Pages (Source: GitHub Actions)."
          exit 0

      - name: Setup Pages (enable if needed)
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
